WITH BaseData AS (
    SELECT
        TC1.CODE_NAME AS DIR_TYPE_NAME,
        TC2.CODE_NAME AS COMMODITY_CATEGORY_NAME,
        MDYS.DIR_TYPE,
        MDYS.COMMODITY_CATEGORY,
        (MDYS.CONTRACE_VOL / 1000) AS CONTRACR_VOL 
    FROM
        M_RESOURCE_MASTER RM 
    LEFT OUTER JOIN V_MMS_DELTA_KW_YAKUJO_SUM MDYS 
        ON RM.RESOURCE_KANRI_NO = MDYS.RESOURCE_KANRI_NO 
        AND MDYS.POW_DELIVERY_DATE = :targetDate 
        AND MDYS.BLOCK_NO = '1' 
    LEFT OUTER JOIN T_CODE TC1 
        ON CONCAT(TC1.CODE_ID, '00') = MDYS.COMMODITY_CATEGORY 
        AND TC1.TARGET_ID = 'COMMODITY_CATEGORY' 
    LEFT OUTER JOIN T_CODE TC2 
        ON TC2.CODE_ID = MDYS.DIR_TYPE 
        AND TC2.TARGET_ID = 'DIR_TYPE' 
    WHERE
        RM.RESOURCE_KANRI_NO = :resourceKanriNO 
        AND RM.START_YYYYMMDD <= :startDay 
        AND RM.END_YYYYMMDD >= :endtDay
),
CountsByDirType AS (
    SELECT 
        DIR_TYPE_NAME, 
        DIR_TYPE,
        COMMODITY_CATEGORY,
        COUNT(*) AS CNT
    FROM BaseData
    GROUP BY DIR_TYPE_NAME, DIR_TYPE, COMMODITY_CATEGORY
),
Cat4000 AS (
    SELECT *
    FROM BaseData
    WHERE COMMODITY_CATEGORY = '4000'
),
Cat3100_3200_2200 AS (
    SELECT *
    FROM BaseData 
    WHERE COMMODITY_CATEGORY IN ('3200', '3100', '2200') 
    AND COALESCE((SELECT MAX(CNT) FROM CountsByDirType WHERE COMMODITY_CATEGORY IN ('4000', '2100', '1000')), 0) = 0 
    AND COALESCE((SELECT MAX(CNT) FROM CountsByDirType WHERE COMMODITY_CATEGORY IN ('3200', '3100', '2200')), 0) > 1 
),
Cat4000_2 AS (
    SELECT
        DIR_TYPE_NAME,
        TC1.CODE_NAME AS COMMODITY_CATEGORY_NAME,
        DIR_TYPE,
        '4000' AS COMMODITY_CATEGORY,
        CONTRACR_VOL 
    FROM BaseData
    LEFT OUTER JOIN T_CODE TC1 
        ON CONCAT(TC1.CODE_ID, '00') = '4000' 
        AND TC1.TARGET_ID = 'COMMODITY_CATEGORY' 
    WHERE COMMODITY_CATEGORY NOT IN ('4000') 
    AND COALESCE((SELECT MAX(CNT) FROM CountsByDirType WHERE COMMODITY_CATEGORY IN ('3200', '3100', '2200')), 0) > 0 
    AND COALESCE((SELECT MAX(CNT) FROM CountsByDirType WHERE COMMODITY_CATEGORY IN ('2100', '1000')), 0) > 0 
),
CatSingle AS (
    SELECT *
    FROM BaseData
    WHERE COMMODITY_CATEGORY NOT IN ('4000') 
    AND COALESCE((SELECT MAX(CNT) FROM CountsByDirType WHERE COMMODITY_CATEGORY NOT IN ('4000')), 0) = 1
)
SELECT * FROM Cat4000
UNION ALL 
SELECT * FROM Cat3100_3200_2200 
UNION ALL 
SELECT * FROM Cat4000_2 
UNION ALL 
SELECT * FROM CatSingle;
